### ISSUE TITLE
travis doesn't deploy assets anymore

### ISSUE THREAD

**Issue by Klumbumbus** [osmlab/editor-layer-index#433] opened 2018-03-08 20:07 UTC
I just made 3 commits. Travis failed, but I can't find a hint or an error message in the Job log at https://travis-ci.org/osmlab/editor-layer-index/builds/350985394?utm_source=github_status&utm_medium=notification so it is hard to find out what was wrong with my commits.

**Comment by bhousel** [comment] 2018-03-08 20:59
Errors are there, but need to expand the triangle to see them...

<img width="978" alt="screenshot 2018-03-08 15 58 16" src="https://user-images.githubusercontent.com/38784/37176168-8db7ea02-22e9-11e8-9da7-0c698f72e180.png">

**Comment by Klumbumbus** [comment] 2018-03-09 17:10
OK, then let's convert this issue to "Travis doesn't work anymore" :)

**Comment by bhousel** [comment] 2018-03-09 17:32
I'm 👍 on getting rid of the auto-deploy stuff.  I'm not convinced that it's worth the extra complexity just to avoid running `make` sometimes on a project that doesn't really have that much activity to begin with.

**Comment by Klumbumbus** [comment] 2018-03-09 17:44
Without this new feature Github users (like me) rely one someone else to generate the files after a creating a commit or PR. Or changes of the generated files are included in the next commit with `make` which is confusing. Also Quick updates of the generated files reduces the workload to maintain https://josm.openstreetmap.de/wiki/ImageryCompare

**Comment by bhousel** [comment] 2018-03-09 19:54
> Without this new feature Github users (like me) rely one someone else to generate the files after creating a commit or PR. Or changes of the generated files are included in the next commit with make which is confusing. Also Quick updates of the generated files reduces the workload to maintain https://josm.openstreetmap.de/wiki/ImageryCompare

I understand that it's nice to not depend on someone actually running `make`.  But it's also faster for me to run `git pull`, `make`, and `git push` (20 sec) than to track down what's wrong with this publisher code (who knows how long).

**Comment by Klumbumbus** [comment] 2018-03-09 19:58
cc @grischard

**Comment by tyrasd** [comment] 2018-03-10 09:43
> I'm not convinced that it's worth the extra complexity just to avoid running make

FWIW, I find it really convenient not having to think about the make step anymore. :relaxed:

**Comment by tyrasd** [comment] 2018-03-10 09:45
also the automated deploy eliminates potential conflicts between PRs after we have added the timestamp field into the generated assets in https://github.com/osmlab/editor-layer-index/pull/385

**Comment by tyrasd** [comment] 2018-03-10 09:49
on topic: this problem seems to be an upstream issue: https://github.com/travis-ci/travis-ci/issues/9312

**Comment by grischard** [comment] 2018-03-10 10:06
It's important to make the editing process more newbie-friendly. I hope that it can be a simple way for mappers to dip their toes into the technical side of OpenStreetMap.

As @tyrasd pointed out, it's not as easy as the git summersault that used to be enough. `make` won't run without the python modules, which means a lot of yak shaving of learning about virtual environments, and maybe even having to install python.

In the past, many commits were made without regenerating the index.

**Comment by grischard** [comment] 2018-03-10 10:09
Temporary fix in c17606f

**Comment by Klumbumbus** [comment] 2018-03-10 11:53
It seems something is still wrong with travis. See https://github.com/osmlab/editor-layer-index/commit/6efcba06798712c08c2efa9cfe30e85339fbef7d and https://github.com/osmlab/editor-layer-index/commit/fd3c3c91c0c49df85a58a6b6fa2bdfa0aa3eafe5 It reverted the deletion of the file.

**Comment by grischard** [comment] 2018-03-10 12:41
Hmm, that might be caused by the `skip-cleanup: true` part of my travis config. I'll look into it.

**Comment by grischard** [comment] 2018-03-11 20:50
I can't really reproduce this anymore. Very strange.

**Comment by tyrasd** [comment] 2018-03-11 21:43
> I can't really reproduce this anymore. Very strange.

It may have been caused by me pushing two commits shortly after each other: 6efcba06798712c08c2efa9cfe30e85339fbef7d and 285f46aba32e8c317d510b638e9f433c12a09b75.
Travis seemed a bit confused, I think: see https://travis-ci.org/osmlab/editor-layer-index/builds, especially https://travis-ci.org/osmlab/editor-layer-index/builds/351666755 says:

>  This job was cancelled because the "Auto Cancellation" feature is currently enabled, and a more recent build (#1003) for branch gh-pages came in while this job was waiting to be processed.

where the newer build was triggered by travis' deploy commit for my first commit – still, travis shouldn't have added the deleted file :man_shrugging: maybe pushing to a different branch [as discussed in another thread](https://github.com/osmlab/editor-layer-index/issues/236#issuecomment-366990266) would prevent such issues?

**Comment by grischard** [comment] 2018-03-11 22:29
Hah, Github should have a  🤷‍♂️ reaction! I can't even think of how it can have known about that deleted file if it was working on the current head.

Yeah, let's do this if it happens again.

**Comment by tyrasd** [comment] 2018-03-13 10:37
@grischard 

travis didn't deploy my changes from 501f95a685b5aa7c297d1245d18323b04bcd5428 in https://travis-ci.org/osmlab/editor-layer-index/builds/352762906:

> Skipping a deployment with the pages provider because a custom condition was not met

is that because of what you commented in 69ea852fa93427f497fd4932d859544a4ca24b83 :thinking: ?

**Comment by grischard** [comment] 2018-03-13 11:30
Yeah, maybe (#286) that's because the license_url property isn't reproduced in `imagery.xml` which I use as a canary for deploys. It's hard to detect whether changes to `sources/` happened during a relevant commit.

**Comment by tyrasd** [comment] 2018-03-13 13:26
Ok, I see. But is it right that we only need this check/condition because we push to the same branch as the input data, in order to avoid ending up in an infinite loop of travis rebuilding the repo over and over again in an infinite loop? If so, we could solve this quirk by deploying to a different branch.

**Comment by grischard** [comment] 2018-03-13 13:36
Another small effect is that we don't deploy on non-imagery changes.

Looking at the environment variables, another check could be that the previous commit wasn't by travis.

**Comment by grischard** [comment] 2018-03-16 13:56
> Looking at the environment variables, another check could be that the previous commit wasn't by travis.

Note to self: try `git log -1 --pretty=format:'%an'`

**Comment by grischard** [comment] 2018-03-26 11:54
Hopefully fixed in 180116b just now.

**Closed by grischard** 2018-03-26 11:54 UTC
