### ISSUE TITLE
Getting Low Res sections of USGS Topo Map, why?

### ISSUE THREAD

**Issue by gregcrago** [osmlab/editor-layer-index#279] opened 2017-01-16 20:36 UTC
![fuzzy topo in id editor - arkansas](https://cloud.githubusercontent.com/assets/7635234/21998176/15bd204c-dbe8-11e6-8122-c14bb719f7a7.PNG)

Working on ID Editor 2.0.2 with OpenStreetMap.org in Arkansas, USA
N34° 25.480' W91° 39.840'
Trying to add a River and while moving toward the South, along the river, I see LOW Resolution and High Resolution images of USGS Topo map.

How can I see HIGH RESOLUTION data always?
Greg

**Comment by iandees** [comment] 2017-01-16 20:43
Hi Greg, you're seeing this because the USGS seems to have stopped supporting the imagery server we use for these backgrounds. The high resolution you're seeing is the cached data that others have looked at before this problem showed up. I run the tiling server that interacts with the USGS and am trying to find someone there that can help us get this valuable mapping resource back, but my hopes aren't high.

**Comment by gregcrago** [comment] 2017-01-16 21:00
Thanks for the feedback. I didn't know if it was a memory issue on my side
with FireFox or Chrome browsers.
Yes, please try to get the High Res back. I use it all the time for adding
elements to the OSM map.

Any chance of being on a 'watch list' so I can be notified if/when the High
Resolution images are back. Then I can "Go back to work"

Greg

**Comment by iandees** [comment] 2017-01-16 21:04
Let's close this one as a duplicate of https://github.com/osmlab/editor-layer-index/issues/151. If you click the subscribe button on the right side of that ticket you'll get notified when something happens.

**Closed by iandees** 2017-01-16 21:04 UTC
