### ISSUE TITLE
Default imagery doesn't load in JOSM

### ISSUE THREAD

**Issue by elevenchars** [osmlab/editor-layer-index#2337] opened 2024-05-27 13:36 UTC
When I set the JOSM preference described in the README and refresh my default imagery sources, nothing shows up
```
imagery.layers.sites	[https://osmlab.github.io/editor-layer-index/imagery.xml]
```
I wasn't able to see any errors. The default JOSM imagery.layers.sites value works.

**Comment by ZeLonewolf** [comment] 2024-07-07 01:49
Please re-open.  The README should not include steps which do not work.

**Comment by cicku** [comment] 2024-07-07 02:32
@ZeLonewolf How did you know that?

**Comment by ZeLonewolf** [comment] 2024-07-07 02:35
I attempted these steps and also found that they do not work in JOSM. 

That means that the README either needs to change to have the correct steps, or else be updated to reflect that ELI doesn't work in JOSM.

**Comment by cicku** [comment] 2024-07-07 02:35
I don't think so?

![image](https://github.com/osmlab/editor-layer-index/assets/686438/8307e3a8-fdf8-44be-a258-0801caedb3c1)
![image](https://github.com/osmlab/editor-layer-index/assets/686438/18522824-6435-4972-9229-9b59434f9afe)

**Comment by ZeLonewolf** [comment] 2024-07-07 02:42
I tested on JOSM build 19128 on Ubuntu, added the ELI URL to that key in preferences, re-loaded in the imagery list, and got an empty list as a result:

![image](https://github.com/osmlab/editor-layer-index/assets/3254090/f7485cda-d666-4c75-8369-f528b5cbb0c7)
![image](https://github.com/osmlab/editor-layer-index/assets/3254090/8fd45a4f-3b6a-482d-b517-206591310f58)
![image](https://github.com/osmlab/editor-layer-index/assets/3254090/6f752455-18ef-4b66-9896-9c8708955adf)

**Comment by ZeLonewolf** [comment] 2024-07-07 02:45
I also see in the logs:
```
2024-07-06 22:43:57.755 INFO: GET https://osmlab.github.io/editor-layer-index/imagery.xml -> HTTP/1.1 200 (421 ms; 1.16 MB)
```
So it seems that JOSM pulls down the file successfully and then maybe has a bug later on. Perhaps a bug in the latest version of JOSM.

**Comment by cicku** [comment] 2024-07-07 02:47
Thanks, but you really need to check with JOSM. I won't troubleshoot further when I cannot reproduce.

This issue sounds like a JOSM bug since day 1 and that's why I marked it as invalid, and I will insist on the decision to close it.

**Comment by iandees** [comment] 2024-07-07 02:48
FWIW, I appended it to the list of items in the preference, hit OK, and reopened JOSM. It didn't make any change to the imagery list. I removed the existing JOSM default imagery URL, kept the ELI one, hit OK, and JOSM loaded it without a problem.

**Closed as not planned** 2024-07-07 02:48 UTC
Labels: invalid

**Comment by ZeLonewolf** [comment] 2024-07-07 03:15
ELI not loading documented in:
https://josm.openstreetmap.de/ticket/23785
