### ISSUE TITLE
Texas imagery

### ISSUE THREAD

**Issue by simonpoole** [osmlab/editor-layer-index#281] opened 2017-01-27 21:01 UTC
https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/north-america/us/tx/TexasOrthophoto.geojson claims that this imagery is from 2012 however at least in some places it seems to be substantially better quality and more recent than both bing and mapbox.

Anybody know if it is really so old?

**Comment by tyrasd** [comment] 2017-01-28 08:52
related: #149

**Comment by talllguy** [comment] 2017-03-31 04:03
@simonpoole It appears that the `start_date` is 2012, but there is no `end_date` given (see [CONTRIBUTING.md](https://github.com/osmlab/editor-layer-index/blob/gh-pages/CONTRIBUTING.md#imagery-dates)). [According to the layer index](https://txgi.tnris.org/login/path/ecology-fiona-poem-romeo/layers), the latest imagery on this service is 2017.

Perhaps we can update the `end_date` to 2017?

**Comment by simonpoole** [comment] 2017-05-25 20:58
@talllguy well if it is continuously updated that might be misleading too, the real question is if it shouldn't have the "best" attribute set so that it gets used instead of bing in the editors.

**Comment by Andrew-Matheny** [comment] 2017-05-25 22:40
I can confirm that there is 2017 imagery based on my local knowledge of the Dallas area. This has been my go-to source for mapping for the past ten months.

I'm not at my work computer, but I believe TNRIS has the tile service configured to display the tiles for the state from whatever the latest year they acquired imagery for that given area. It looks like they strategically purchase urban areas once a year, but rural areas may only get an update every few years or so.

**Comment by simonpoole** [comment] 2017-05-26 11:41
There isn't a really good way to handle differences in quality/age in one layer in the current design of this project. As a workaround you could add a second entry with polygons just for the urban areas.

**Comment by bhousel** [comment] 2017-07-27 15:01
> @talllguy well if it is continuously updated that might be misleading too, the real question is if it shouldn't have the "best" attribute set so that it gets used instead of bing in the editors.

@simonpoole I would never set the "best" attribute unless Bing was very bad or unusable in that area.

For example, the New Jersey orthos are maybe 1-2 years newer than Bing but _much_ slower to load, so I only use them as a second alternative.  They are good to map new developments and recent construction.   Newer doesn't automatically mean best.

**Comment by simonpoole** [comment] 2017-07-27 15:16
@bhousel I have to admit that it has never occurred to me that we might want to use best to indicate anything outside of imagery quality, resolution and currency. 

Naturally how fast the layer loads is an usability issue, but I'm not convinced that silently not displaying the most current layer is the solution.

**Comment by rbuffat** [comment] 2021-02-01 20:17
Closing this issue as the referenced source is no longer existing. If there is still an issue with one of the now existing texas sources we should reopen the issue: https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/north-america/us/tx

**Closed by rbuffat** 2021-02-01 20:17 UTC
Labels: imagery
