### ISSUE TITLE
VBMP Most Recent Imagery broken

### ISSUE THREAD

**Issue by no1lakersfan2007** [osmlab/editor-layer-index#2544] opened 2024-11-02 19:16 UTC
For the past month, when trying to use the layer for VBMP Most Recent Imagery (Virginia) all I get is a black background. It is as if the imagery is no longer working for this layer. It appears it has been updated recently however the link to make the layer show may not be correct anymore. It would be nice to have this working again because in some areas this imagery is the most recent.

**Comment by arch0345** [comment] 2024-11-03 07:20
This was fixed back in https://github.com/osmlab/editor-layer-index/pull/2536, however this won't be reflected in iD/Rapid until a new release of the editor is made

(duplicate of #2534)

**Closed as not planned by arch0345** 2024-11-03 07:20 UTC
Labels: duplicate
