### ISSUE TITLE
New Services URL for Delaware Imagery

### ISSUE THREAD

**Issue by talllguy** [osmlab/editor-layer-index#1472] opened 2022-02-25 14:18 UTC
The Delaware Imagery services have been migrated as of February 2022. The imagery was first added in #165

## New links

- [2017](https://imagery.firstmap.delaware.gov/imagery/rest/services/DE_Imagery/DE_Imagery_2017/ImageServer)
- [2012](https://imagery.firstmap.delaware.gov/imagery/rest/services/DE_Imagery/DE_Imagery_2012/ImageServer)

## Announcement

FirstMap Update - February 2022
Greetings from the FirstMap team! 2022 is well underway and we are excited about the updates we have to share.
We are at the end of the migration to FirstMap 2.0, and we have some important dates in this issue. We are planning to begin the decommission process for FirstMap 1.0 servers as early as March 1st, 2022. We only have a couple of items still being tested. Once they go live everything in FirstMap 1.0 will be shut down. Please utilize the Lookup Tool and Service Update Guide mentioned in the Other Important Information section below to find the new FirstMap 2.0 URL's and tips for updating ArcGIS Online content.
If you are having any issues with any of your web maps or applications, please check the URL's to make sure they are configured to point to FirstMap 2.0. Any items that haven't been updated can still be accessed, but will not work properly until they are updated. Please don't hesitate to contact us if you need any assistance.
As always, thank you for your interest in FirstMap.
RETIRING DATA & SERVICES in FirstMap 1.0
•	RETIRING as of 2/28/2022: The remaining services that have been fully migrated to FirstMap 2.0 will be shut down beginning February 28th, 2022. This includes [Private Services](https://firstmap.dti.state.de.us/arcgis/rest/services/) and [Public Services](https://firstmap.gis.delaware.gov/arcgis/rest/services/).
•	REMINDER: ALL Aerial Imagery Services have been retired. They have been replaced by [new Web Mercator](https://imagery.firstmap.delaware.gov/imagery/rest/services/DE_Imagery) and [new State Plane](https://imagery.firstmap.delaware.gov/imagery/rest/services/DE_Imagery_SP) services in FirstMap 2.0.
•	A full list of what has been migrated is available on [data.delaware.gov](https://data.delaware.gov/). Search for FirstMap, then browse the [Delaware FirstMap Endpoints](https://data.delaware.gov/Government-and-Finance/Delaware-FirstMap-Endpoints/k4qa-iwrc) list. If you are aware of anything that has been missed please contact us.
30-DAY NOTICES:
•	CHANGING 3/20/22: Election_Districts_2012 - Redundant attributes will be removed, and EDRD_2012 will change to RDED_2012 (note the flip in the order of the district numbers) effective 3/20/22. A test service (DE_Political_Boundaries_Pending) is published for your review: Map Service and Feature Service.
•	ARCHIVING 3/20/22: The DE_Archive_Plans Map Service and Feature Service is being replaced with DE_Transportation_Plans_Public (listed below) and will be archived on 3/20/22.
•	REMOVING 3/20/22: DE_Impervious_Surface_2017 Map Service has been replaced with DE_Impervious (listed below) and will be removed on 3/20/22.
•	REMOVING 3/20/22: DE_LULC_2017_Condensed Map Service and Feature Service has been replaced with DE_LULC (listed below) and will be removed on 3/20/22.
•	REMOVING 3/20/22: Census_2020 Map Service and Feature Service has been replaced with DE_Census_2020 (listed below) and will be removed on 3/20/22.
•	REMOVED: The Bicycle Network Model layers (layers 5-18) were removed from the [DE_Multimodal service](https://enterprise.firstmap.delaware.gov/arcgis/rest/services/Transportation/DE_Multimodal/FeatureServer) and published in a separate DE_Bicycle_Network_Model service (listed below).
•	Please see our Service Change Policy for more details on the process to make changes to FirstMap services.
DATA & SERVICES in FirstMap 2.0
•	ONGOING: FirstMap 2.0 items can be found in [ArcGIS Online](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdelaware.maps.arcgis.com%2Fhome%2Findex.html&data=04%7C01%7CMark.Prettyman%40delaware.gov%7C8ba672668bf046b9700708d9f550dacd%7C8c09e56951c54deeabb28b99c32a4396%7C0%7C0%7C637810549881871740%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2B7tp%2FgZccbPY6OA7HZLcvK6ZYN7Zw%2FHhEVh5G4P1L20%3D&reserved=0) and are marked as authoritative with new icons.
•	NEW: 2020 Enacted House and Senate Districts - [Map Service ](https://enterprise.firstmap.delaware.gov/arcgis/rest/services/PlanningCadastre/DE_Impervious/MapServer)and Feature Service. PLEASE NOTE: This is a temporary service. The new district boundaries will take effect following the November 2022 election and the existing Senate Districts and House of Representatives Districts will be updated after the completion of the election.
•	NEW: DE_Bicycle_Network_Model - Map Service and Feature Service
•	NEW: DE_Transportation_Plans_Public - Map Service and Feature Service
•	NEW: DE_Fire_Districts - Map Service and Feature Service
•	NEW: Impervious Surface - Map Service (2007, 2012, 2017), [2007 Image Service](https://imagery.firstmap.delaware.gov/imagery/rest/services/PlanningCadastre/DE_Impervious_2007/ImageServer), [2012 Image Service](https://imagery.firstmap.delaware.gov/imagery/rest/services/PlanningCadastre/DE_Impervious_2012/ImageServer), and [2017 Image Service](https://imagery.firstmap.delaware.gov/imagery/rest/services/PlanningCadastre/DE_Impervious_2017/ImageServer)
•	NEW: LULC (2007, 2007 Revised, 2012, 2017) - Map Service and Feature Service
•	NEW: Historic Markers - Map Service and Feature Service
•	NEW: DE_Census_2020 - Map Service and Feature Service
MAPS, APPS, HUBS, AND MORE
•	BROADBAND HUB: We are excited to share a new Hub put together by the Location Intelligence team for the State's Broadband Initiative. The Hub consists of two maps, the first map allows constituents to search their address to find if they have been identified as unserved. If their address is not located, but they are unserved, then a survey is available for them to report their address. The second map shows provider coverage areas as well as the unserved points. Check out the Broadband Hub for more information.
•	Have a map, app, hub or great project to share in the newsletter or FirstMap gallery? Contact the Location Intelligence team.
OTHER IMPORTANT INFORMATION
•	FirstMap 2.0 Services Migration Help document: For a detailed step by step guide to help with updating your ArcGIS Online content to point to the new FirstMap 2.0 endpoints, please refer to our [Service Update Guide](https://firstmap.delaware.gov/arcgis-repo/pdfs/FirstMap2/DEAGOLServiceUpdateGuide.pdf).
•	Lookup Tool: A searchable list of FirstMap 1.0 features (layers) and their corresponding FirstMap 2.0 URL's is available online! Go to [data.delaware.gov](https://data.delaware.gov/), search for FirstMap, then browse the [Delaware FirstMap Endpoints](https://data.delaware.gov/Government-and-Finance/Delaware-FirstMap-Endpoints/k4qa-iwrc) list. If the FirstMap 2.0 URL field is blank, please view the comments to see if it may have been retired or is not migrating. If there aren't any comments, that means it will be migrated but just hasn't been finished yet. If there are any datasets or features you are interested in that aren't listed, please contact the FirstMap team.
•	Connect to FirstMap 2.0: For instructions to help you connect to FirstMap 2.0 resources, we have provided instructions on our FAQ page. In the section "How do I connect to FirstMap" go to the [Information Sheet](https://firstmap.delaware.gov/contentFolder/pdfs/state/FM2ServiceConnect.pdf) for details.
•	Training Resources: Additional documents and a variety of resources to help expand your esri GIS knowledge and skills are available on the [FirstMap Training Hub](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftraining-delaware.opendata.arcgis.com%2F&data=04%7C01%7CMark.Prettyman%40delaware.gov%7C8ba672668bf046b9700708d9f550dacd%7C8c09e56951c54deeabb28b99c32a4396%7C0%7C0%7C637810549881871740%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=gkFJVBkyFNjUl2Pk3NN7Sy%2FW%2FbXS4p5IWCQyp1ZxIAc%3D&reserved=0).
UPCOMING MEETINGS
•	Delaware Geographic Data Committee (DGDC): Meetings in 2022 are set for August 11th, and November 17th. See the DGDC Home Page for more information.
•	Geospatial Mid-Atlantic Users Group (GeoMUG, formerly Esri-MUG): One-Day virtual meeting is planned for Earth Day, April 22, 2022. See their [website](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fesri-mid-atlantic-user-group-esri-mug.hub.arcgis.com%2F&data=04%7C01%7CMark.Prettyman%40delaware.gov%7C8ba672668bf046b9700708d9f550dacd%7C8c09e56951c54deeabb28b99c32a4396%7C0%7C0%7C637810549881871740%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=JeeYM37Pi1u5J6xrcUWmftt%2FTefLDVeIDVQM29QW7IU%3D&reserved=0) for more information.
•	Delmarva GIS 2022 Conference: The next Delmarva GIS Conference will be held on May 13th, 2022 at the Hyatt Place in Dewey Beach, Delaware. There will be pre and post conference activities. Be sure to check the [conference website](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.degis.org%2F&data=04%7C01%7CMark.Prettyman%40delaware.gov%7C8ba672668bf046b9700708d9f550dacd%7C8c09e56951c54deeabb28b99c32a4396%7C0%7C0%7C637810549881871740%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=A6rn1I%2Beez9WIbbC4DTN3bgvrvvE2RG8bMAeHQUZaNo%3D&reserved=0) often for updates.
•	TUGIS Maryland Geospatial Conference: The next TUGIS conference will be held on August 4th, 2022. Check their [conference website](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftugisconference.com%2F&data=04%7C01%7CMark.Prettyman%40delaware.gov%7C8ba672668bf046b9700708d9f550dacd%7C8c09e56951c54deeabb28b99c32a4396%7C0%7C0%7C637810549881871740%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Zt0n2A3aC6HvOpt8ebs1%2BMhbarHDo46dJmipA2bcEn8%3D&reserved=0) for more information.
•	MAC URISA 2022 Conference: Join MAC URISA from October 12th to October 14th, 2022 in Atlantic City, NJ. Registration is opening soon. Check out their [conference website](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmacurisaconf2022-urisa.hub.arcgis.com%2F&data=04%7C01%7CMark.Prettyman%40delaware.gov%7C8ba672668bf046b9700708d9f550dacd%7C8c09e56951c54deeabb28b99c32a4396%7C0%7C0%7C637810549881871740%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=zzpjKueuNl7sPwGE7PcZCQI2uDZHYBzQ2m5r0IxB%2BN8%3D&reserved=0) for more information.
For more information or assistance e-mail the FirstMap support team at [FirstMap@delaware.gov](mailto://firstmap@delaware.gov).

**Comment by cicku** [comment] 2022-02-28 18:09
Hi Elliott!

Would you please confirm if this is a duplicate of https://github.com/osmlab/editor-layer-index/pull/1242?

**Closed as completed** 2022-03-04 16:08 UTC
Labels: invalid

**Comment by talllguy** [comment] 2022-03-07 02:24
Sorry I missed this. I did search but didn't find that referenced ticket. I figured it was new since it was just announced in February
