### ISSUE TITLE
USGS Imagery should include the whole US

### ISSUE THREAD

**Issue by arch0345** [osmlab/editor-layer-index#1506] opened 2022-04-29 22:12 UTC
Currently the geojson for [USGS Imagery](https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/north-america/us/USGSImagery.geojson) only covers the contiguous United States. However, this imagery also covers other parts of the US (namely Alaska, Hawaii, Puerto Rico, US Virgin Islands, Guam, Northern Mariana Islands, and American Samoa).

**Comment by grischard** [comment] 2022-05-02 04:28
Is the JOSM imagery index polygon correct?

**Comment by arch0345** [comment] 2022-05-02 05:43
> Is the JOSM imagery index polygon correct?

No, [it also](https://josm.openstreetmap.de/mapsview?entry=USGS%20Imagery) only includes the contiguous United States.

**Comment by cicku** [comment] 2022-08-16 02:54
Alaska: https://github.com/osmlab/editor-layer-index/commit/fb1fd10e1f4cd8c93b4faec8a0871fb2029c2bf9

**Comment by cicku** [comment] 2022-08-17 01:41
@rbuffat I added the Alaska but the check script returned an error saying that the bbox is not on the shell...Which I worry if this will cause any issue because the bbox extends into the Eestern Hemisphere?

![image](https://user-images.githubusercontent.com/686438/185015922-7e874f94-ac7d-4ef9-95fd-85d9b3bfca28.png)

**Comment by rbuffat** [comment] 2022-08-29 08:36
@cicku I try to look at this during the next few days. Sorry, I'm currently a bit too occupied by other things.

**Comment by grischard** [comment] 2022-08-30 14:32
If going over the 180th meridian creates an issue, the polygon can be split in two on it.

**Comment by rbuffat** [comment] 2022-09-02 15:01
@cicku I could not reproduce the `the bbox is not on the shell` issue. In https://github.com/osmlab/editor-layer-index/commit/fb1fd10e1f4cd8c93b4faec8a0871fb2029c2bf9 the issue was that when changing from Polygon another layer of [ ] needs to be added: 

<details>


> [2.1.6. Polygon](https://geojson.org/geojson-spec.html#polygon)
> For type "Polygon", the "coordinates" member must be an array of LinearRing coordinate arrays.

> [2.1.7. MultiPolygon](https://geojson.org/geojson-spec.html#multipolygon)
> For type "MultiPolygon", the "coordinates" member must be an array of Polygon coordinate arrays.


</details>

**Comment by cicku** [comment] 2022-09-02 15:04
I reverted my MultiPolygon change since it was generated from other tools.

<details>
Run find sources -name \*.geojson | xargs python scripts/check.py
/home/runner/work/editor-layer-index/editor-layer-index/scripts/check.py:120: UserWarning: sources/europe/no/KartverketBuildings.geojson icon should be disembedded to save 1.15 KB
  warnings.warn(f"{filename} icon should be disembedded to save {round(iconsize/1024.0, 2)} KB")
ERROR:root:Error in sources/north-america/us/USGSImagery.geojson : sources/north-america/us/USGSImagery.geojson geometry is not valid: Hole lies outside shell[-179.93410400391 50.8337[11](https://github.com/osmlab/editor-layer-index/runs/7849992002?check_suite_focus=true#step:5:12)54832]
</details>

https://github.com/osmlab/editor-layer-index/runs/7849992002?check_suite_focus=true

**Comment by rbuffat** [comment] 2022-09-02 15:05
In https://github.com/osmlab/editor-layer-index/pull/1576 I added your added Polygon and the check seems fine.

**Comment by rbuffat** [comment] 2022-09-02 15:47
>  Hole lies outside shell[-179.93410400391 50.8337

This is the same issue. For Polygon Geojson uses an array of rings.  The first ring is the outer area (=shell), each subsequent ring are holes.  A ring is encoded as `[ [lon1, lat1], [lon2, lat2], ..]`. 

Thus in your case the second ring (the Alaska part), is considered a hole. But as it is outside of the mainland US, it is outside of the shell. 

As Polygons are arrays of rings, and Multipolygon are arrays of Polygons, one additional level of [ ] must be added when switching the geometry type from Polygon to MultiPolygon.

**Comment by cicku** [comment] 2022-09-07 14:03
Oh thanks for the answer, it appears that I may have a format issue.

Closing as the issue is solved

**Closed as completed by cicku** 2022-09-07 14:03 UTC

**Comment by arch0345** [comment] 2022-09-09 03:11
It appears that only Alaska, Puerto Rico, and US Virgin Islands were added. USGS Imagery also covers Hawaii, Guam, and American Samoa.

Edit: it looks like imagery in Northern Mariana Islands isn't visible at higher zoom levels
<img width="618" alt="image" src="https://user-images.githubusercontent.com/85302075/189543459-79b1dd3b-3e83-49df-bef3-cee0f21dde60.png">

**Comment by cicku** [comment] 2022-09-11 15:39
Yes you are right, but USGS imagery is not very useful in these areas considering its clarity there. I will add.
