### ISSUE TITLE
Multiple sources in Poland marked as best

### ISSUE THREAD

**Issue by maro-21** [osmlab/editor-layer-index#1079] opened 2021-03-07 13:48 UTC
Someone set https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/europe/pl/Geoportal2OrthophotomapHighQuality(aerialimage).geojson
as best imagery for Poland.

This imagery is from 2014!! Setting it as best for Poland will make people draw nonexistent buildings from old maps. We already have photos from 2020 which should be default.
Please remove it as best layer as well as change the description which should be in English.

**Comment by Asteliks** [comment] 2021-03-09 21:43
duplicate of https://github.com/openstreetmap/iD/issues/8383

**Comment by matkoniecz** [comment] 2021-03-10 08:45
> duplicate of openstreetmap/iD#8383

Not a duplicate as change is required in editor-layer-index repository.

**Comment by Asteliks** [comment] 2021-03-10 10:01
> > duplicate of [openstreetmap/iD#8383](https://github.com/openstreetmap/iD/issues/8383)
> 
> Not a duplicate as change is required in editor-layer-index repository.

Look second dot here: https://github.com/openstreetmap/iD/issues/8383#issue-823929447

and the replay to the second dot here: https://github.com/openstreetmap/iD/issues/8383#issuecomment-794488081

**Comment by rbuffat** [comment] 2021-03-12 10:46
First, thanks all for your feedback. @matkoniecz @maro-21 @Asteliks 

Currently, there are multiple sources in Poland that are marked as best:

```
> grep -nr best .    
./Geoportal2EwidencjabudynkówWMS.geojson:9:        "best": true,
./PoznaOrthophotomapBiezaca(aerialimage).geojson:13:        "best": true,
./WrocawOrthophotomap2018(aerialimage).geojson:11:        "best": true,
./Geoportal2Punktyadresowe.geojson:9:        "best": true,
./Geoportal2Nazwyulic.geojson:9:        "best": true,
./Geoportal2OrthophotomapHighQuality(aerialimage).geojson:10:     "best": true,
./Geoportal2Orthophotomap(aerialimage).geojson:9:        "best": true,
```

The definition for "best" in ELIs schema is `Whether this imagery is the best source for the region`, which can be interpreted differently. The main issue here seems to be that Geoportal2Orthophotomap(aerialimage).geojson contains the latest imagery where Geoportal2OrthophotomapHighQuality(aerialimage).geojson contains the imagery with the highest resolution.
Both sources contain aggregated imagery of Poland from different years, which is a case where the data model of ELI shows its limits

@matkoniecz proposes in https://github.com/osmlab/editor-layer-index/issues/1083 to rename both layers to make the difference more clear. A further possibility would be to also add a start_date and end_date to the sources: https://github.com/osmlab/editor-layer-index/blob/cb3a79d0ad5f971708ca1e94bf036cc84581932c/schema.json#L112-L120 
Currently, none of these two sources seem to have a date assigned. However, I'm not sure if the data is taken into account by OSM editors (e.g. iD). 
 
If one of the layers is "better" in most cases, it would also be possible to assign the best flag to only one of the two sources.

**Comment by matkoniecz** [comment] 2021-03-12 11:13
> A further possibility would be to also add a start_date and end_date to the sources: 

That would not help as both are mosaic of imagery from wildly different dates

**Comment by Asteliks** [comment] 2021-03-12 11:25
The problem with start and end dates is that:
- we do not know the start and end dates
- because these layers are technically aggregators start and end dated may be different for every region
- someone would need to update the start and end date every time the source changes
- we do not know when these layers are updated

**Comment by matkoniecz** [comment] 2021-03-12 11:27
> we do not know the start and end dates

http://www.gugik.gov.pl/aktualnosci/2019/13.08.2018-informacje-o-aktualnosci-ortofotomapy-w-geoportalu (though geoportal.gov.pl website is partially down for me)

**Comment by Asteliks** [comment] 2021-03-12 11:30
Hey if you want to analyze every tile for the entire country ones a month to check the dates, sure it can be done but it will be time consuming

**Comment by matkoniecz** [comment] 2021-03-12 12:12
I am not claiming that it is a good idea ( https://github.com/osmlab/editor-layer-index/issues/1079#issuecomment-797424009 ), just wanted to let people know that it is rare case of aerial imagery with exact capture dates being available. What sometimes is useful.

**Comment by rbuffat** [comment] 2021-03-28 19:20
I merged the proposition of @matkoniecz in https://github.com/osmlab/editor-layer-index/issues/1083, thus I'm closing this issue for now. 

@Asteliks @maro-21 @matkoniecz Please leave a comment or PR if you feel that more / other needs to be done.

**Closed as completed by rbuffat** 2021-03-28 19:20 UTC

**Comment by matkoniecz** [comment] 2021-03-28 20:17
I would consider removing "best" from high resolution imagery, as it requires some ability to use it properly.
