### ISSUE TITLE
ELI does not load in latest JOSM

### ISSUE THREAD

**Issue by ZeLonewolf** [osmlab/editor-layer-index#2388] opened 2024-07-08 13:22 UTC
Follow-on from #2337 which is locked

This issue is [confirmed](https://josm.openstreetmap.de/ticket/23785#comment:1) by the JOSM team who state:

> The problem is that we require an imagery category in the XSD. I don't know the reasoning for that off the top of my head.
The reason why things changed recently is we do more validation of requirements in the XSD that cannot be done via XSD due to technical limitations. 
> See [source:trunk/resources/data/maps.xsd@19130:638-640,686-688#L638](https://josm.openstreetmap.de/browser/trunk/resources/data/maps.xsd?marks=638-640%2C686-688&rev=19130#L638)[​](https://josm.openstreetmap.de/export/19130/josm/trunk/resources/data/maps.xsd#L638) .
> Anyway, the "easy" solution would be to add an arbitrary category to each entry. It does look like the ELI has a category property that can be used (and the JOSM category might be based off of that, I don't know).

Note this issue occurs on the _latest_ version of JOSM, which I confirmed on build 19128.  The JOSM team confirms this is a recent change.

From this description it appears that ELI may no longer be compatible with JOSM.

**Comment by simonpoole** [comment] 2024-07-08 13:29
I believe the issue is simply that https://github.com/osmlab/editor-layer-index/blob/gh-pages/scripts/convert_xml.py doesn't actually convert the _category_ field.

**Comment by cicku** [comment] 2024-07-08 22:50
@simonpoole I can merge the PR but I need to get some clarification, does it mean whenever JOSM releases some breaking changes, we are required to keep up with them?

I’m asking because bringing a new field may break other clients but I can’t tell.

**Comment by simonpoole** [comment] 2024-07-09 06:28
@cicku 

It isn't a new field, it is one that, at the time, was introduced coordinated with JOSM (that's the reason that some of the values are very JOSMish) and ELI actually requires it iirc. 

It is just that nobody added it to the JOSM compatible output and nobody noticed because JOSM didn't check its input.

Now you do have a point wrt keeping things in sync with JOSM. For a while there was an effort to, even if neither party was and is willing to give up the parallel effort, to at least keep the widely used information and support synced and  compatible so that users could use either index. I believe there is still some value to that and if it just involves fixing a trivial python script, I don't see any reason to not do so.

All that said, please don't merge yet, because of a minor emergency yesterday I didn't get around to testing in particular the output needs to be checked against the XSD (obviously best that would be included in the CI, but that is likely too much work if there isn't a ready made python way of doing that, which I haven't investigated).

@grischard ping

**Comment by simonpoole** [comment] 2024-07-09 09:49
> All that said, please don't merge yet, because of a minor emergency yesterday I didn't get around to testing in particular the output needs to be checked against the XSD (obviously best that would be included in the CI, but that is likely too much work if there isn't a ready made python way of doing that, which I haven't investigated).

I've fixed a number of things that failed validation (some which had "always" been wrong), can be merged now from my pov. Naturally no guarantees.

**Closed as completed** 2024-08-19 05:44 UTC
