### ISSUE TITLE
Layers 'NC OneMap Latest Orthoimagery (Infrared)' and 'NC OneMap Latest Orthoimagery (Natural Color)' do not work

### ISSUE THREAD

**Issue by CorruptComputer** [osmlab/editor-layer-index#1517] opened 2022-05-25 12:11 UTC
The editor defaults to these layers in some places, and they do not load anything but a black background. 
Could they be removed, or at least made to not be the default?

Screenshot of the issue:
![image](https://user-images.githubusercontent.com/5573038/170258295-8c621a59-d0f6-4270-8a4b-6748f0a278b7.png)

OSM link to location where the issue is present: 
https://www.openstreetmap.org/edit#map=20/35.25973/-80.71864

**Comment by cicku** [comment] 2022-05-27 16:58
Duplicate of #1507

**Comment by cicku** [comment] 2022-05-27 16:59
BTW Infrared layer is not broken. If it does not load, it means the server is overloaded.

**Closed as not planned by cicku** 2022-05-27 16:58 UTC
